version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    network_mode: host
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dhc-app:
    image: ${REGISTRY}/dhc-ktor-app:${IMAGE_TAG}
    container_name: dhc-app
    network_mode: host
    environment:
      - NCP_ACCESS_KEY=${NCP_ACCESS_KEY}
      - NCP_SECRET_KEY=${NCP_SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - MONGO_CONNECTION_STRING=mongodb://localhost:27017/dhc
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongodb_data: