ktor:
  application:
    modules:
      - com.mashup.dhc.ApplicationKt.module
  deployment:
    port: 8080

db:
  mongo:
    connectionString: $MONGO_CONNECTION_STRING
    database:
      name: "dhc"
    maxPoolSize: 20

ncp:
  accessKey: $NCP_ACCESS_KEY
  secretKey: $NCP_SECRET_KEY
  bucketName: $BUCKET_NAME
  region: "kr-standard"
  endpoint: "https://kr.object.ncloudstorage.com"