ktor:
  application:
    modules:
      - com.mashup.ApplicationKt.module
  deployment:
    port: 8080

# MongoDB 설정
db:
  mongo:
    host: "localhost"
    port: "27017"
    database:
      name: "test"
    maxPoolSize: 20