ktor:
  application:
    modules:
      - com.mashup.dhc.ApplicationKt.module
  deployment:
    port: 8080

# MongoDB 설정
db:
  mongo:
    host: "localhost"
    port: "27017"
    database:
      name: "test"
    # 아래는 선택사항입니다
    # user: "mongo사용자"
    # password: "mongo비밀번호"
    maxPoolSize: 20